### PR TITLE
Migrate deprecated constants

### PR DESCRIPTION
**Pull request by ccMatrix**
This pull request changes the deprecated constants that will be removed in HA core 2025.1 to the correspondig class constants. 

Fixes issues #109 and #110

### CODE REVIEW

**Review by Uvve-Dev — APPROVED** [review]
Tested and working on my Side (Weatherstation and Roomsensors give correct Status and receive proper Commands))

**Review by emufan — APPROVED** [review]
ested and working on my Side

**Review by fsedarkalex — APPROVED** [review]

**Comment by Skyless81** [comment]
The current version 2.1.1 still contains the errors mentioned

**Comment by nyn3x** [comment]
this should also fix #119

**Review by peribeir — APPROVED** [review]
Sorry for the late approval. Thanks for the cnotribution.

**Comment by nyn3x** [comment]
@peribeir - even though this PR was merged into master no new release seemed to be created. 🤔

**Pull request merged**
